In [ ]:
 my_tuple=('aman','222',700,44.4)

In [ ]:
my_dict={"roll no:cb.en.u4cse20207","Name: Sai Sumanth","DOB 23 may 2003"}
print(my_dict)

{'roll no:cb.en.u4cse20207', 'Name: Sai Sumanth', 'DOB 23 may 2003'}


In [ ]:
from google.colab import drive

In [ ]:
import numpy as np
from numpy import random
np.random.seed(5)
x=random.randint(10,size=(3,2))
print(x)

[[3 6]
 [6 0]
 [9 8]]


In [ ]:
y = random.rand()
print(y)
abs(-1234)

0.08982103773760686


1234

In [ ]:
z = random.randint(20,90)
print(z)

82


In [ ]:
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)

[12, 15, 13, 11, 14]
14
[15, 13, 12]


In [ ]:
f = open('test.txt','w')
f.write('The King is Dead, Long Live The King')
f.close()
f = open('test.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

In [ ]:
test = 'The King is Dead, Long Live The King'
array = test.split()
print(test)
print(test[2:5])
print(test[2:])

The King is Dead, Long Live The King
e K
e King is Dead, Long Live The King


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[1])
print(len(arr))

[4 5 6]
2


In [ ]:
arr = random.randint(20,size=(10))
print(arr)
x = arr.reshape(2,5)
print(x)

[12 13 11  1 15 18  9 10  9  9]
[[12 13 11  1 15]
 [18  9 10  9  9]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[1])
print(arr[0][1],arr[1][1])
print(len(arr))

[4 5 6]
2 5
2


In [ ]:
ar=np.array([1,2,3,4,5,6,7,8,9,0])
print(ar)
ar=ar.reshape(2,5)
print(ar)

[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
a15=[1,2,3]
a15=np.full((3),9)
print(a15)

[9 9 9]


In [ ]:
a16=[2,4,5]
print(sum(a16))

11


In [ ]:
a17=[77,74,75]
prod=1
for i in a17:
  prod*=i
print(prod)

427350


In [ ]:
from scipy import stats
a18=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean=",np.mean(a18))
print("Median=",np.median(a18))
print("Mode=",stats.mode(a18))
print("Max=",max(a18))
print("Min=",min(a18))

Mean= 12.461538461538462
Median= 2.0
Mode= ModeResult(mode=array([1]), count=array([4]))
Max= 56
Min= 1


In [ ]:
a19=[1, 1, 4, 5, 5, 5, 7]
a19=list(set(a19))
a19.sort()
print(a19)

[1, 4, 5, 7]


In [ ]:
a20=[1,2,3]
b20=[0,1,1]
print(np.dot(a20,b20))

5


In [ ]:
a21=[[2,-12],[1,-5]]
x,y=np.linalg.eig(a21)
print(x,y)

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [ ]:
a22=[[11, 22, 11, 31], [25, 33, 31, 28]]
print(np.corrcoef(a22))

[[1.         0.15997968]
 [0.15997968 1.        ]]
